version: "3"
services:
  build:
    container_name: docker_cross_demo_build
    image: rocproject/cross-aarch64-linux-gnu:gcc-7.4
    volumes:
      - .:/app
    working_dir: /app
    command: sh docker/build.sh
    tty: true

  app:
    container_name: docker_cross_demo_run
    image: arm64v8/busybox:1.31.0
    volumes:
      - ./output/arm-Release:/app
    working_dir: /app
    command: ./app
    tty: true
